import type { EditingAdjustments, HslAdjustments } from "@/types";

const defaultHsl: HslAdjustments = {
  red: { hue: 0, saturation: 0, luminance: 0 },
  orange: { hue: 0, saturation: 0, luminance: 0 },
  yellow: { hue: 0, saturation: 0, luminance: 0 },
  green: { hue: 0, saturation: 0, luminance: 0 },
  aqua: { hue: 0, saturation: 0, luminance: 0 },
  blue: { hue: 0, saturation: 0, luminance: 0 },
  purple: { hue: 0, saturation: 0, luminance: 0 },
  magenta: { hue: 0, saturation: 0, luminance: 0 },
};

export function createDefaultAdjustments(): EditingAdjustments {
  return {
    exposure: 0,
    contrast: 0,
    highlights: 0,
    shadows: 0,
    whites: 0,
    blacks: 0,
    temperature: 0,
    tint: 0,
    vibrance: 0,
    saturation: 0,
    texture: 0,
    clarity: 0,
    dehaze: 0,
    curveHighlights: 0,
    curveLights: 0,
    curveDarks: 0,
    curveShadows: 0,
    hsl: {
      red: { ...defaultHsl.red },
      orange: { ...defaultHsl.orange },
      yellow: { ...defaultHsl.yellow },
      green: { ...defaultHsl.green },
      aqua: { ...defaultHsl.aqua },
      blue: { ...defaultHsl.blue },
      purple: { ...defaultHsl.purple },
      magenta: { ...defaultHsl.magenta },
    },
    sharpening: 0,
    masking: 0,
    noiseReduction: 0,
    colorNoiseReduction: 0,
    vignette: 0,
    grain: 0,
    grainSize: 50,
    grainRoughness: 50,
    rotate: 0,
    vertical: 0,
    horizontal: 0,
    scale: 100,
    aspectRatio: "original",
    opticsProfile: false,
    opticsCA: false,
  };
}
