export const CANVAS_NUMERIC_FIELD_IDS = [
  "brightness",
  "exposure",
  "contrast",
  "clarity",
  "temperature",
  "tint",
  "saturation",
  "vibrance",
  "hue",
  "highlights",
  "shadows",
  "whites",
  "blacks",
  "texture",
  "dehaze",
  "vignette",
  "grain",
  "grainSize",
  "grainRoughness",
  "blur",
  "dilate",
  "sharpening",
  "sharpenRadius",
  "sharpenDetail",
  "masking",
  "noiseReduction",
  "colorNoiseReduction",
  "glowIntensity",
  "glowMidtoneFocus",
  "glowBias",
  "glowRadius",
] as const;

export type CanvasImageNumericFieldId = (typeof CANVAS_NUMERIC_FIELD_IDS)[number];
